# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class GitPm < Formula
  desc "Smart wrapper for gh cli that validates conventional commits, creates prs, waits"
  homepage "https://github.com/claylo/git-pm"
  url "https://github.com/claylo/git-pm/archive/refs/tags/v1.0.2.tar.gz"
  sha256 "8f9c7096c81aee090c7369bdfc92b2ae5ebb6ce53f1954316840151a6a5e65e1"
  license "MIT"

  def install
    bin.install "git-pm" => "git-pm"
  end
end
