# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class GitPm < Formula
  desc "Smart wrapper for gh cli that validates conventional commits, creates prs, waits"
  homepage "https://github.com/claylo/git-pm"
  url "https://github.com/claylo/git-pm/archive/refs/tags/v1.0.1.tar.gz"
  sha256 "c2f802bd869ef2354f0f231295babf5870798ff0cc8df5a30f3c09c425d64199"
  license "MIT"

  def install
    bin.install "git-pm" => "git-pm"
  end
end
