# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class GitPm < Formula
  desc "Smart wrapper for gh cli that validates conventional commits, creates prs, waits"
  homepage "https://github.com/claylo/git-pm"
  url "https://github.com/claylo/git-pm/archive/refs/tags/v1.0.0.tar.gz"
  sha256 "25a8e707d954ae8488eb74e5682044641c5e30708d1485764cf412c85f42b9c3"
  license "MIT"

  def install
    bin.install "git-pm" => "git-pm"
  end
end
